package SETA.Data;

import java.util.Random;

/**
 * Represents a ride request generated by the SETA process
 */
public class RideRequest {
    private int id;
    private Position startPosition;
    private Position endPosition;

    /**
     * Constructor that generate starting and final position randomly
     * @param id id of the ride request
     */
    public RideRequest(int id) {
        this.id = id;
        Random rn = new Random();

        //this.startPosition = new Position(rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX),
        //        rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX));

        this.startPosition = new Position(2,3);

        //this.endPosition = new Position(rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX),
        //        rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX));

        this.endPosition = new Position(4,1);

        while(this.startPosition.equals(this.endPosition)){
            this.endPosition = new Position(rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX),
                    rn.nextInt((Position.LAST_CELL_INDEX - Position.FIRST_CELL_INDEX + 1) + Position.FIRST_CELL_INDEX));
        }
    }

    /**
     * Returns the district of the request based on the starting position
     * @return the district number of the request
     */
    public int getDistrict() {
        if(this.startPosition.getX() < 5 && this.startPosition.getY() < 5) {
            return 1;
        } else if(this.startPosition.getX() < 5 && this.startPosition.getY() >= 5){
            return 2;
        } else if(this.startPosition.getX() >= 5 && this.startPosition.getY() < 5){
            return 3;
        } else {
            return 4;
        }
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Position getStartPosition() {
        return startPosition;
    }

    public void setStartPosition(Position startPosition) {
        this.startPosition = startPosition;
    }

    public Position getEndPosition() {
        return endPosition;
    }

    public void setEndPosition(Position endPosition) {
        this.endPosition = endPosition;
    }
}
